version: '3'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec foreman start
    volumes:
      - .:/app
      - bundle_path:/bundle
    environment:
      - BUNDLE_PATH=/bundle
      - BUNDLE_APP_CONFIG=/app/.bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  bundle_path:
